### ISSUE TITLE
Impulse comparison: order of arguments wrong for Julius

### ISSUE THREAD

**Issue by adefossez** [jonashaag/audio-resampling-in-python#1]
Hi @jonashaag , I was looking at the impulse response and trying to understand why it was looking so wrong with Julius, and why so little attenuation was present above the old Nyquist frequency.

Well, it seems you gave the arguments in the wrong order for Julius, it should be `old_sr`, `new_sr`, just as resampy, but you passed the opposite.

**Comment by jonashaag** [comment]
Oops, thanks for pointing it out. Happy to accept a PR.

**Comment by adefossez** [comment]
Let me send that out soon :)

**Comment by jonashaag** [comment]
If you want, feel free to suggest other changes to the notebook as well. I haven't really put much thought into it except for adding more libraries.

**Comment by adefossez** [comment]
Thanks @dofuuz  for the fix. However, it seems on the nbviewer site, the notebook doesn't get updated, at least for me. Weirdly if instead of using the `master` blob, I use the explicit last commit, it displays fine:
https://nbviewer.jupyter.org/github/jonashaag/audio-resampling-in-python/blob/5720cbebbde1aa6d79c82e9eb9e3be73c3e2fc93/Audio%20Resampling%20in%20Python.ipynb

vs

https://nbviewer.jupyter.org/github/jonashaag/audio-resampling-in-python/blob/master/Audio%20Resampling%20in%20Python.ipynb

Is this happening only for me? I tried adding `?flush_cache=true` to the URL, following [nbviewer FAQ](https://nbviewer.jupyter.org/faq#why-is-nbviewer-showing-an-outdated-version-of-my-notebook) but this doesn't seem to have any effect. Well the issue is probably on nbviewer side, but I wanted to check if you already experienced that.

**Comment by jonashaag** [comment]
Same issue for me, maybe wait a few days? Idk

**Comment by adefossez** [comment]
Yep, it's resolved now :) Closing the issue!
